### ISSUE TITLE
Broken Rendering?

### ISSUE THREAD

**Issue by Soyuz247** [Querz/mcaselector#65] opened 2019-12-18 11:23 UTC
https://imgur.com/a5RGKl0
https://imgur.com/PseNUj9

I tried clearing the cache multiple times but it still broken

**Comment by Querz** [comment] 2019-12-18 12:20
What Minecraft version did you use to generate the world?
Are you using any mods?
What version of the MCA Selector are you using?
What Java version are you using to run the MCA Selector?
When you enable debug mode in the settings, do you see any errors in the console?

**Comment by Soyuz247** [comment] 2019-12-18 14:49
@Querz  

I use 1.12.2 
Yes, 78 mods to be exact, but i have tried deleting the mods and reinstall each of them just to make sure which one conflicts with MCA selector and i can't find any

I am using the newest version of MCA selector ( 1.9.3) and i use the newest java version straight from Oracle (https://www.java.com/en/download/manual.jsp)

i don't see any errors in debug mode either

**Comment by Soyuz247** [comment] 2019-12-18 14:50
Also, i tried creating a new world, somehow the problem still kinda exist
 Like when i try opening the new world in mca selector, sometimes it works, sometimes the same error occurs

**Comment by Querz** [comment] 2019-12-19 13:53
If you use mods that add blocks to the game, keep in mind that those blocks are not supported to be rendered and will appear in black. I can also not guarantee for modded worlds to display at all or any of the other features like the chunk filter or chunk import to work correctly, people are at their own risk there.

If you want to send me a sample region file that doesn't render correctly i can have a quick look at it and tell you more though.

**Comment by Soyuz247** [comment] 2019-12-20 10:22
ok, weird thing is, areas that have mod added blocks render normally, while areas that blocks are 100% vanilla ( even the buildings as well) have failed to render ( some of those areas to be precise )

**Comment by Soyuz247** [comment] 2019-12-22 06:09
https://www.curseforge.com/minecraft/mc-mods/jeid

I think this is the mod that creates conflicts

**Comment by Querz** [comment] 2019-12-23 12:42
Yes, this is probably the cause. There might be a problem with chunk versions saved differently with this mod. The MCA Selector decides based on the chunk version whether to load it as a 1.13 chunk or a 1.12.2 chunk. If the version number is still in the range of 1.12.2 or below, it will try to parse that modded 1.12.2 chunk as an actual 1.12.2 chunk with block ids instead of the block palette.

But without having a sample .mca file i really can't say much about the actual cause of the problem.

**Comment by Soyuz247** [comment] 2019-12-24 04:41
.mca? You mean a region file?

**Comment by Soyuz247** [comment] 2019-12-24 05:10
Ok so this is the link for the whole region folder
https://drive.google.com/open?id=1vg_KlGacSj028-uG8XQSOSojv5h3sUUG
This is the link for one of the region files ( i picked the region where the problem exists )
https://drive.google.com/open?id=1hXdp_oX9mjXQ-AgcN-DuoZshkdZ3JpBn

**Comment by Soyuz247** [comment] 2019-12-28 11:30
Have you found any errors?

**Comment by Querz** [comment] 2020-01-02 10:10
I had a look at the data in that file. The chunks are saved with DataVersion 1343 (which is 1.12.2), but uses a mix of block ids, block data values and the 1.13 palette.

The mod certainly does not save chunks with the 1.13 data format. The reason why anything is rendered at all is because the mod is still using 1.12.2 block ids at least for the vanilla blocks, which are mapped to a palette which in turn is ignored by the MCA Selector because it is reading the chunks as 1.12.2 chunks.

Biomes appear to be saved in the correct 1.13 format, but they are ignored when rendering because the chunk is read as a 1.12.2 chunk. This will only affect rendering of the nether though.

Updating the DataVersion to something above 1343 and rerendering the map will also not work, because as mentioned before the format is not compatible with 1.13. Updating the DataVersion will result in nothing being rendered at all.

I will not write a fix for this as this is is a result of a modded version of the game and i cannot guarantee any of the functionality of the MCA Selector for modded worlds, but in this specific case at least chunk deletion and chunk export should work fine.

**Closed** 2020-01-03 12:43 UTC
Labels: wontfix
