### ISSUE TITLE
Javafx?

### ISSUE THREAD

**Issue by NJR1202** [Querz/mcaselector#218] opened 2021-06-10 12:49 UTC
I have Java 16.1 installed. Yet when I want to download the latest version of MCA selector, I get a pormpted to download "javafx" for Java 16.1. 

I cannot seem to find javafx, I have no idea what it is, nor how to resolve the issue. 

What must I do? 

Kind regards,
NJR

![MCA download issue](https://user-images.githubusercontent.com/85685802/121527685-f5eeb180-c9fa-11eb-8364-bcd4f3798dc9.png)

**Comment by emnbdx** [comment] 2021-06-10 13:00
All needed informations at end of readme ;
https://github.com/Querz/mcaselector#download-and-installation

**Comment by Querz** [comment] 2021-06-11 07:09
Duplicate of https://github.com/Querz/mcaselector/issues/216

**Closed by Querz** 2021-06-11 07:09 UTC
