### ISSUE TITLE
Weird rendering of chunks 1.13.3

### ISSUE THREAD

**Issue by ComputerJock** [Querz/mcaselector#157] opened 2020-12-03 18:18 UTC
**Describe the bug**
I have a 1.16.4 world. It was not specifically upgraded from 1.16.3 via the Minecraft launcher's Edit->Optimize World option. The 1.16.3 world was originally 1.14.4, pruned with MCAselector, upgraded to 1.16.3 via the Optimize World option, and then uploaded to our server. The server was later upgraded to 1.16.4. Therefore, from what I understand, the world contains a mixture of 1.16.3 and 1.16.4 chunks.

Running Minecraft and revisiting those areas, there is nothing unusual.

**To Reproduce**
I would assume that the minimum steps would be
1. Create a 1.16.3 world.
2. Upgrade the game/server to 1.16.4 >without< using the Optimize World option
3. Fly around in the (now) 1.16.4 world to create new 1.16.4 chunks
4. Run MCAseclector on the world.

5. The weird renderings seem to appear mostly in ocean biomes but that is, perhaps, due to the fact that they are more easily visible. It also appears that the "weird" stuff is an overlay of some sort rather that a completely incorrect render.

**Expected behavior**
Previously, MCAselector did not display these weird chunk renderings >however< I have never run MCSselector on a world that had not previous been completely upgraded via the launcher's Optimize world feature.

Additional note: MCAselector 1.13.2 also renders these chunks incorrectly.

**Screenshots and other files**
![Untitled 1](https://user-images.githubusercontent.com/23107501/101067130-c6974d80-355c-11eb-8ca8-6aadb1795cf8.png)

I noticed that there were a bunch of folders in the cache/ folder even though I had specifically cleared them via (in MCAselector) View->Clear Cache & View->Clear All Cache. I manually removed them all before starting MCAselector for this bug report.
[debug.log](https://github.com/Querz/mcaselector/files/5637988/debug.log)

The debug log is attached. 

**Environment (please complete the following information):**
- OS: win7x64
- Java version: "C:\Program Files\Java\jre1.8.0_181\bin\java.exe"
- Version: MCAselector 1.13.2 & 1.13.3 

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world.
 1.16.4 upgrading from 1.16.3
- Relevant debug messages from Minecraft.
 None
- Mods used that change Minecraft save files or add blocks to the game.
These are the mods we have installed, but none of the incorrect chunks were deliberately targeted by any mod, nor do the chunks appear damaged in any way when in-game.
autoconfig1u-3.3.1.jar
config-2-4.8.3.jar
fabric-api-0.27.1+1.16.jar
fabric-carpet-1.16.4-1.4.19+v201125.jar
fabricmod_VoxelMap-1.10.14_for_1.16.4.jar
Hwyla-Mod-Fabric-1.16.3.jar
litematica-fabric-1.16.4-0.0.0-dev.20201103.184101.jar
lithium-fabric-mc1.16.4-0.6.0.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
minihud-fabric-1.16.4-0.19.0-dev.20201103.184029.jar
modmenu-1.14.13+build.19.jar
NoFog-1.16.2b1-Fabric.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
sodium-fabric-mc1.16.3-0.1.0.jar
WI-Zoom-1.3-MC1.16.4.jar
worldedit-fabric-mc1.16.3-7.2.0-dist.jar
WorldEditCUI-1.16.2+01.jar

- Previously used programs to alter the world files.
MCAselector to prune 1.14.4 chunks

**Comment by Querz** [comment] 2020-12-04 02:26
Thanks for this detailed bug report.

I can not reproduce this problem generating a new world in 1.16.3, optimizing it with 1.16.4 and generating new chunks in 1.16.4. Could you upload one of the .mca files where this problem occurs please?

**Comment by ComputerJock** [comment] 2020-12-04 02:41
From bottom of MCAselector window: chunk 14,-13 region 0,-1
Note that I am doing all this on a backup of the world which I downloaded from the server -- of course this is where I am seeing these strange artifacts.
[r.0.-1.mca.zip](https://github.com/Querz/mcaselector/files/5640261/r.0.-1.mca.zip)

**Comment by ComputerJock** [comment] 2020-12-04 02:59
Don't know if this is anyway applicable. When we started our world in 1.14, the hosting company strongly suggested we use Spigot. So I did -- this is the first time I've rented a server. We skipped 1.15 since 1.16 was the Nether update and I did not want to do two prune-chunks jobs. As part of our 1.16 upgrade, I switched to vanilla with the Fabric loaded (modded with the list above) -- we were getting tired of farms not working due to Spigot's "optimizations".

**Comment by Querz** [comment] 2020-12-04 03:34
Thanks, i figured it out.
Minecraft saves blocks using a per-section palette (a section is a 16x16x16 piece of a chunk). The palette is a list of all blocks and block states this section contains, so a matrix of 4096 values can use that as a reference.
This palette should always contains "air" as a block state on index 0. Assuming that this is always the case, MCA Selector skips all blocks which are referring to index 0.
It appears that in the chunks where the problem occurs "air" is *not* on index 0, which makes those chunks render in this weird way.

Example: This is how it should be:
![image](https://user-images.githubusercontent.com/8278330/101117828-2e46aa80-35e8-11eb-9b9a-b37975f259d9.png)
And *this* is how it looks like in the chunks with the problem:
![image](https://user-images.githubusercontent.com/8278330/101117924-5d5d1c00-35e8-11eb-908a-af4bb4a7316d.png)
As you can see "air" is occupying index 0 in the first section, but the last index in the second section.

I wrote a quick fix for that which i would like to revisit in the future (because it might slow down rendering significantly, haven't tested that yet though). Here's a compiled version with that fix you can try:
[mcaselector-1.13.3-palette-fix.zip](https://github.com/Querz/mcaselector/files/5640427/mcaselector-1.13.3-palette-fix.zip)
Please let me know if you see any significantly slower render times :)

**Comment by ComputerJock** [comment] 2020-12-04 03:48
I've not run MCAselector enough to give you a good comparison of render times -- the fixed version rendering time was completely acceptable. 

I again manually removed all the contents of the AppData\Local\mcaselector\cache before running the jar. It looks like the fix works. Attached is the screenshot. Thank you very much for the fix -- I wonder if it was caused by the mixture of 1.16.3 & 1.16.4 chunks?
![Untitled 1](https://user-images.githubusercontent.com/23107501/101119610-51099c80-35b1-11eb-9131-b598d25ca0b5.png)

**Comment by Sicarine** [comment] 2021-01-24 02:01
Reporting that I encountered this bug just through normal gameplay in 1.16.5. I also saw this bug appear in Xisumavoid's HC video. 

The patched jar did resolve the issue.

Just putting that here, since this bug does not appear to be an isolated case. 

I have a suspicion the weird palette indexing may be due to the lithium mod, but I can't verify that at the moment.

**Comment by Querz** [comment] 2021-02-26 09:39
Fixed in release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14).

**Closed by Querz** 2021-02-26 09:39 UTC
Labels: bug
