### ISSUE TITLE
When I press the "Up" key, it lags and continues moving.

### ISSUE THREAD

**Issue by OneCamperBoi** [Querz/mcaselector#233] opened 2021-06-30 06:33 UTC
When I push the up key, it continues scrolling until I close the program.

1. Open the program
2. Load a world from ZIP file
3. Press the "Up" arrow for 2-3 seconds
4. As you can see, it will continue scrolling. 

**Environment (please complete the following information): **
- OS: Windows 10 version 21H2
- Java version: 1.8.0_291-b10
- Version 1.17

**Comment by Querz** [comment] 2021-07-01 13:29
duplicate of https://github.com/Querz/mcaselector/issues/229

**Closed by Querz** 2021-07-01 13:29 UTC

**Comment by OneCamperBoi** [comment] 2021-07-05 12:02
Please fix it! Your app is incredibly good, but this bug ruins the experience. I must use the "Go-to" function every time I want to go up.
