### ISSUE TITLE
program crashes when the jar-path contains an exclamation mark

### ISSUE THREAD

**Issue by noxifoxi** [Querz/mcaselector#283] opened 2021-11-23 02:11 UTC
The path on this example is: `\\debian\nox\minecraft\tools!`, it's a network share in my case but it doesn't matter, it also happens on a folder on my Windows PC.
Somehow the exclamation mark gets lost and it crashes with this error output:
```
java.lang.Exception: failed to decode jar file
        at net.querz.mcaselector.debug.Debug.dumpException(Debug.java:105)
        at net.querz.mcaselector.text.Translation.getResourceListing(Translation.java:334)
        at net.querz.mcaselector.text.Translation.<clinit>(Translation.java:195)
        at net.querz.mcaselector.Main.main(Main.java:37)
java.nio.file.NoSuchFileException: \\debian\nox\minecraft\tools
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
        at net.querz.mcaselector.text.Translation.getResourceListing(Translation.java:332)
        at net.querz.mcaselector.text.Translation.<clinit>(Translation.java:195)
        at net.querz.mcaselector.Main.main(Main.java:37)
Exception in thread "main" java.lang.IllegalArgumentException: unsupported locale en_GB
        at net.querz.mcaselector.text.Translation.load(Translation.java:287)
        at net.querz.mcaselector.Main.main(Main.java:37)
```

**Comment by Querz** [comment] 2021-11-30 00:32
Duplicate of https://github.com/Querz/mcaselector/issues/276, see [comment](https://github.com/Querz/mcaselector/issues/276#issuecomment-968194745)

**Closed by Querz** 2021-11-30 00:32 UTC
