### ISSUE TITLE
When deleting chunks in a region, another unrelated chunk keeps getting reset also

### ISSUE THREAD

**Issue by GIDustin** [Querz/mcaselector#416] opened 2023-06-08 16:54 UTC
**Describe the bug**
Using MCASelector to prune chunks in my world before updating to 1.20.  Selecting chunks outside of my built areas.  When I delete any chunk in a specific region, there is a single chunk in that region that also gets deleted.  Is there something wrong with that chunk that is causing this?

**To Reproduce**
You would need my world I guess to replicate.  Open world, delete any chunk in that region, watch as another unrelated chunk also disappears

**Expected behavior**
Only the selected chunks get reset

**Screenshots and other files**
Attached screenshots of the issue.
![Orig](https://github.com/Querz/mcaselector/assets/8001432/ecd1430b-1404-4482-b092-a9d5a0c36a2f)
![done](https://github.com/Querz/mcaselector/assets/8001432/d1f25de6-944d-4b0d-b152-68b7bb483bd1)

Attached debug logs where I try to remove only the top right chunk in the region
[mcaselector.log](https://github.com/Querz/mcaselector/files/11691061/mcaselector.log)

World is fairly large.  If you need it, let me know which specific files are needed.

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 20?  I used the windows installer on this site yesterday
- Version of MCA Selector 2.2

**Comment by Querz** [comment] 2023-06-09 00:50
I am not able to reproduce this with a fresh 1.19.4 world in a fully generated region r.2.-1.mca with the same amount of selected chunks.
Do you mind uploading those mca files here, specifically the `r.2.-1.mca` from the world's `region`, `entities` and `poi` folder (if they exist)?

**Comment by GIDustin** [comment] 2023-06-09 01:28
Sure.  I got those files in here, and on my system, the issue exists with just these 3 files.

[MCASelector_Issue416.zip](https://github.com/Querz/mcaselector/files/11699318/MCASelector_Issue416.zip)

**Comment by Querz** [comment] 2023-06-09 12:28
Fixed in release 2.2.1.

**Closed by Querz** 2023-06-09 12:28 UTC
